#!/usr/bin/env bash

# ============================================================================ #

# Packages #

# Virtual M. and Docker
export list00="qemu-kvm qemu-guest-agent libvirt-clients libvirt-daemon-system bridge-utils virt-manager ovmf dnsmasq docker.io"

# Essentials [+VM/SoC]
export list01="beep inxi curl nmap parallel smartmontools tmux zip unzip dialog udpcast traceroute arp-scan net-tools netdiscover rdesktop scrcpy speedtest-cli whois btop rsnapshot rclone openssh-server net-tools haveged arp-scan cifs-utils netdiscover w3m w3m-img iotop htop lm-sensors samba samba-dsdb-modules samba-vfs-modules sshpass speedtest-cli traceroute docker.io build-essential libatasmart-bin btrfs-progs"

# Server [No VM/SoC]
export list02="$list00 $list01 gpm xinit xorg openbox pavucontrol caja epiphany-browser gparted gnome-disk-utility terminator cmatrix"

# Desktop
export list03="$list01 shotcut ubuntu-restricted-extras scrcpy adb pavucontrol printer-driver-all rdesktop terminator hardinfo cpu-x qbittorrent dconf-editor filezilla thunderbird thunderbird-locale-pt-br rss-glx xscreensaver xscreensaver-data xscreensaver-data-extra xscreensaver-gl-extra xscreensaver-gl k3b drawing mypaint gimp audacity kodi vlc aisleriot gnome-mines gnome-mahjongg kpat fluidsynth cmatrix"

# WINE
export list04="winehq-staging winetricks"

# ============================================================================ #

# For Ubuntu 22.04 and beyond!
export NEEDRESTART_MODE=a
export DEBIAN_FRONTEND=noninteractive

# Variaveis Globais
export processname=0; export validmail=0; export process=0; export status=0; export pkg=0
export password=0; export password1=0; export password2=0; export password3=0
export report=0

function menuA {
apt purge needrestart cloud-init snapd unattended-upgrades plank deja-dup evolution evolution-data-server bluez blueman bluetooth -y
apt autoremove -y
apt update
apt upgrade -y
}

function menuB {
var0=$(dialog --title 'Linite' --backtitle "L I N I T E" --menu " " 0 0 0 \
A 'Virtual Machine' \
B 'Essentials [All]' \
C 'Server [No VM/SoC]' \
D 'Desktop [No VM/SoC]' \
E 'WINE [No VM/SoC]' \
F 'Tools [All]' \
G 'Beep!' \
X 'Sair' 2>&1 > /dev/tty )
case "$var0" in
A) alpha ;;
B) beta ;;
C) gamma ;;
D) delta ;;
E) games ;;
F) curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/main/tools | sudo bash ; menuB ;;
G) wget https://raw.githubusercontent.com/urbancompasspony/beep/main/beep -O /home/administrador/.beep.sh ; beep ; start ;;
X) echo "Saindo..." && exit ;;
esac
}

# ============================================================================ #

# Virtual M. and Docker
function alpha {
dialog --title "Menu" --yesno "Deseja instalar os seguintes pacotes? \n
$list00" 25 40
[ $? = 0 ] && {
  installer "$list00"
  user0
  menuB
  }
menuB
}

# Essentials [+VM/SoC]
function beta {
dialog --title "Menu" --yesno "Deseja instalar os seguintes pacotes? \n
$list01" 25 40
[ $? = 0 ] && {
  installer "$list01"
  user0
  servicesoff
  sysctlconf
  journaladjust
  netplan1
  smbconfig
  menuB
  }
menuB
}

# Server [No VM/SoC]
function gamma {
dialog --title "Menu" --yesno "Deseja instalar os seguintes pacotes? \n
$list02" 25 40
[ $? = 0 ] && {
  installer "$list02"
  user0
  servicesoff
  sysctlconf
  netplan1
  smbconfig
  menuB
  }
menuB
}

# Desktop
function delta {
dialog --title "Menu" --yesno "Deseja instalar os seguintes pacotes? \n
$list03" 25 40
[ $? = 0 ] && {
  installer "$list03"
  dpkg --add-architecture i386
  user0
  servicesoff
  sysctlconf
  journaladjust
  smbconfig
  ppa1
  tmpfstab
  menuB
}
menuB
}

# WINE
function games {
dialog --title "Menu" --yesno "Deseja instalar os seguintes pacotes? \n
$list04" 25 40
[ $? = 0 ] && {
  perfil
  wineinstall
  installer "$list04"
  menuB
}
menuB
}

# ============================================================================ #

function installer {
  apt install $1 --no-install-recommends -y
  }

function user0 {
  export usr1
  usr1=$(dialog --title 'Grupos de Usuário' --backtitle " " --inputbox "Quem vai acessar o LibVirt / Docker?" 10 40 2>&1 > /dev/tty)
  usermod -aG libvirt $usr1
  usermod -aG libvirt-qemu $usr1
  usermod -aG docker $usr1
  }

# ============================================================================ #

function ppa1 {
xorg1=$(ls /tmp/.X11-unix | wc -l)

[ "$xorg1" = "0" ] && {
  dialog --title "Erro" --msgbox "XOrg nao encontrado! Abortando..." 6 40
  menuB
  }

dialog --title "Menu" --yesno "Deseja adicionar os repositórios do TVLite e LinuxUprising/Java?" 10 40
[ $? = 0 ] && {
  add-apt-repository ppa:tv-lite/ppa-git
  apt install tv-lite
  add-apt-repository ppa:linuxuprising/java
  }
}

function servicesoff {
dialog --title "Menu" --yesno "Deseja desativar os processos *-wait-online?" 10 40
[ $? = 0 ] && {
  systemctl disable NetworkManager-wait-online.service
  systemctl mask NetworkManager-wait-online.service
  systemctl disable systemd-networkd-wait-online.service
  systemctl mask systemd-networkd-wait-online.service
  }
}

function perfil {
dialog --title "Menu" --yesno "Deseja modificar o arquivo .profile?" 10 40
[ $? = 0 ] && {
  echo -e "STAGING_RT_PRIORITY_SERVER=90
STAGING_RT_PRIORITY_BASE=90
WINE_RT=15
WINE_SRV_RT=10
STAGING_WRITECOPY=1
STAGING_SHARED_MEMORY=1
WINE_ENABLE_PIPE_SYNC_FOR_APP=1
export __GL_MaxFramesAllowed=1" >> /home/$USER/.profile
  }
}

function sysctlconf {
dialog --title "Menu" --yesno "Deseja modificar o arquivo sysctl.conf?" 10 40
[ $? = 0 ] && {
  echo -e "kernel.sysrq=1
vm.swappiness=10
vm.panic_on_oom=1
kernel.panic=5" >> /etc/sysctl.conf
  }
}

function journaladjust {
dialog --title "Menu" --yesno "Deseja modificar o arquivo journald.conf?" 10 40
[ $? = 0 ] && {
  echo "$password" | sudo -S echo -e "Storage=persistent
SystemMaxUse=5G
SystemKeepFree=10G" >> /etc/systemd/journald.conf
  }
}

function tmpfstab {
dialog --title "Menu" --yesno "Deseja modificar o arquivo fstab.conf?" 10 40
[ $? = 0 ] && {
  echo "$password" | sudo -S echo -e "# Temp to ram!
tmpfs /tmp tmpfs defaults 0 0
tmpfs /var/tmp tmpfs defaults 0 0" >> /etc/fstab
  }
}

function netplan1 {
dialog --title "Menu" --yesno "Deseja modificar o arquivo netplan.yaml?" 10 40
[ $? = 0 ] && {
echo -e "
#network:
#    ethernets:
#        enp4s0:
#            addresses: [192.168.250.10/24]
#            gateway4: 192.168.250.1
#            dhcp4: no
##           optional: true
#            nameservers:
#              addresses: [192.168.250.1]
#              #addresses: [200.225.197.34, 200.225.197.37] 
#              #addresses: [200.175.89.139, 200.175.5.139]
#              #addresses: [8.8.4.4, 8.8.8.8]
#              #addresses: [1.1.1.1, 1.0.0.1]
#    version: 2" >> /etc/netplan/00-installer-config.yaml

echo -e "
#network:
#  ethernets:
#    eth0:
#      dhcp4: true
#      optional: true

#    eth1: # THIS!
#      dhcp4: no
#      optional: true
#      addresses: [172.16.1.2/24]
#  version: 2" >> /etc/netplan/00-installer-config.yaml
  }
}

function smbconfig {
dialog --title "Menu" --yesno "Deseja modificar o arquivo samba.conf?" 10 40
[ $? = 0 ] && {

mv /etc/samba/smb.conf /etc/samba/smb.BKP

echo -e "
##########
# Global #
##########

[global]
#client min protocol = SMB2
#client max protocol = SMB3

server string = Shared
netbios name = shared
workgroup = WORKGROUP

security = user
map to guest = bad user
dns proxy = no

#domain master = yes
#local master = yes
#preferred master = yes
#os level = 255

unix charset = UTF-8
dos charset = ISO8859-1
mangled names = no
read raw = Yes
write raw = Yes

#################
# Audit Modules #
#################

vfs objects = recycle, full_audit, acl_xattr
store dos attributes = yes
map acl inherit = yes

audit:failure = none
full_audit:success = unlinkat renameat
full_audit:prefix = IP=%I|USER=%u|MACHINE=%m|VOLUME=%S
log level = 0 vfs:0

#syslog = 0
recycle:repository = /mnt/shared/Lixeira/%U
recycle:keeptree = yes
recycle:versions = yes
recycle:touch = Yes
recycle:touch_mtime = yes
recycle:noversions = *.tmp,*.temp,*.o,*.obj,*.TMP,*.TEMP
recycle:exclude = *.tmp,*.temp,*.o,*.obj,*.TMP,*.TEMP
recycle:excludedir = /mnt/shared/Lixeira,/recycle,/tmp,/temp,/TMP,/TEMP

##################
# Shared Folders #
##################

[TEMP]
path = /mnt/shared
valid users = administrador
admin users = administrador
guest ok = no
writable = yes
browsable = yes
create mask = 0777
force create mode = 0777
directory mask = 0777
force directory mode = 0777" > /etc/samba/smb.conf
  }
}

function wineinstall {
echo "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_22.04 ./" | sudo tee /etc/apt/sources.list.d/wine-obs.list
wget -qO- https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_22.04/Release.key | sudo tee /etc/apt/trusted.gpg.d/winehq.asc
apt update
}

function beep {
  sudo bash /home/administrador/.beep.sh
  echo "@reboot sleep 60; bash /home/administrador/.beep.sh" >> /tmp/crontab_new
  sudo crontab -l | cat - /tmp/crontab_new > crontab.txt && sudo crontab crontab.txt
}

# ============================================================================ #

function start {
[ "$EUID" -ne 0 ] && {
  echo "Execute esse script como Root!"
  exit
  }

dialog --title "Menu" --yesno "Deseja remover pacotes abaixo e atualizar o sistema? \n \n
needrestart cloud-init snapd unattended-upgrades plank deja-dup evolution evolution-data-server blueman bluetooth" 12 40

[ $? = 0 ] && {
  dpkg --configure -a
  apt install -f

  menuA
  menuB
  }

[ $? = 1 ] && {
  dpkg --configure -a 
  apt install -f

  menuB
  }
}

# Checagem Obrigatória de Dependências:
apt install dialog
timedatectl set-timezone America/Bahia

start
