#!/usr/bin/env bash

# ======================================================================================================================================================== #
# curl -L m.linuxuniverse.com.br | bash
# ======================================================================================================================================================== #

wget -O- https://raw.githubusercontent.com/urbancompasspony/linite/refs/heads/main/model-arm-run > ~/.arm-installer
chmod +x .arm-installer
./.arm-installer
