#!/usr/bin/env bash

# FIRST:
sudo apt install curl wget dialog nano

# sudo pihole uninstall -y

# wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash

nano /etc/hosts
127.0.1.1 cattail

# then:
wget -O- https://raw.githubusercontent.com/urbancompasspony/linite/refs/heads/main/model-linux-deploy-android-run > ~/.model-installer; chmod +x .model-installer; ./.model-installer
