#!/usr/bin/env bash

# ======================================================================================================================================================== #
# curl -L arm.linuxuniverse.com.br | bash -i
# ======================================================================================================================================================== #

MENU_VERSION="v3.2 - 11/06/2025"

export list01="docker.io net-tools speedtest-cli whois netdiscover iperf arp-scan traceroute sshpass network-manager \
libatasmart-bin smartmontools zip unzip p7zip-full 7zip p7zip cifs-utils rsnapshot rclone iotop \
haveged stress lm-sensors cmatrix btop inxi tree dialog btrfs-progs build-essential unrar duf \
openvpn curl nmap parallel openssh-server samba samba-dsdb-modules samba-vfs-modules xinit xorg openbox xdotool xmlstarlet"

# ARM64
export package_2204="linux-modules-extra-raspi "
export package_2404="docker-buildx"

# ======================================================================================================================================================== #

function root_check0 {
  [ "$EUID" -ne 0 ] || {
    clear
    echo "Não execute este script como Root! DICA: Remova o SUDO do comando ou execute-o como usuario local."; echo ""
    exit
  }
}

function welcome0 {
  clear; echo ""; echo "Preparo de Servidor $MENU_VERSION by SuitIT®"; echo ""
  echo "Insira a senha padrao: ubuntu"; echo ""
  sudo echo . >/dev/null
  echo ""; echo "5"; sleep 1; echo "4"; sleep 1; echo "3"; sleep 1; echo "2"; sleep 1; echo "1"; sleep 1
}

function bashconf0 {
  clear; echo "Preparando sistema e configurando BASH"; echo ""
  curl -sSL https://raw.githubusercontent.com/urbancompasspony/bashrc/main/install.sh | bash
}

function timezone0 {
  sudo timedatectl set-timezone Etc/GMT+3
  sudo timedatectl set-local-rtc 1
}

function useless0 {
  clear; echo "Removendo pacotes e desativando servicos inuteis"; echo ""
  sudo apt purge needrestart cloud-init snapd unattended-upgrades plank deja-dup evolution evolution-data-server bluez blueman bluetooth -y

  cat <<EOF | sudo tee /etc/apt/preferences.d/nosnap.pref
# To prevent repository packages from triggering the installation of Snap,
# this file forbids snapd from being installed by APT.
# For more information: https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html
Package: snapd
Pin: release a=*
Pin-Priority: -10
EOF

  sudo apt-mark hold snapd

  sudo systemctl disable systemd-networkd-wait-online.service
  sudo systemctl mask systemd-networkd-wait-online.service
}

function update_arm {
    clear; echo "Atualizando o sistema"; echo ""
    sudo apt update; sudo apt upgrade -y; sudo apt autoremove -y; clear

    echo "Tentando pacotes 24.04...."
    sudo apt install $list01 $package_2404 -y &&
    sync &&

    echo "Tentando pacotes 22.04...."
    sudo apt install $list01 $package_2204 -y &&
    sync &&

    sudo systemctl disable NetworkManager-wait-online.service
    sudo systemctl mask NetworkManager-wait-online.service

    sudo usermod -aG docker administrador
}

function netplan0 {
    echo -e "
#
#network:
#    ethernets:
#        renderer: NetworkManager
#        enp4s0:
#            addresses: [192.168.250.10/24]
#            routes:
#            - to: default
#              via: 192.168.120.254
#            dhcp4: no
##           optional: true
#            nameservers:
#              addresses: [192.168.250.1]
#              #addresses: [200.225.197.34, 200.225.197.37] 
#              #addresses: [200.175.89.139, 200.175.5.139]
#              #addresses: [8.8.4.4, 8.8.8.8]
#              #addresses: [1.1.1.1, 1.0.0.1]
#    wifis:
#      wlan0:
#        dhcp4: true
#        dhcp6: false
#        addresses:
#        - 192.168.4.1/24
#        optional: true
#        access-points:
#          'ctOS RPi':
#            password: '5V06@uso'
#            mode: ap" | sudo tee -a /etc/netplan/00-installer-config.yaml

echo -e "
#
#network:
#  ethernets:
#    eth0:
#      dhcp4: true
#      optional: true

#    eth1: # THIS!
#      dhcp4: no
#      optional: true
#      addresses: [172.16.1.2/24]
#  version: 2" | sudo tee -a /etc/netplan/00-installer-config.yaml
}

function sysctl0 {
    sleep 3; clear; echo "Aplicando recursos extras ao SYSCTL"
    echo -e "kernel.sysrq=1
vm.panic_on_oom=1
vm.swappiness=10
kernel.panic=5
#net.ipv4.ip_forward=1
#net.ipv6.conf.all.disable_ipv6=1
#net.ipv6.conf.default.disable_ipv6=1" | sudo tee -a /etc/sysctl.conf
}

function yaml0 {
  sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_arm64 -O /usr/local/bin/yq
  sudo chmod +x /usr/local/bin/yq
}

function motd0 {
    sleep 3; clear; echo "Ajustando tela de boas vindas do servidor"
    sudo rm -R /etc/update-motd.d/*
    curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/main/MOTD/00-header | sudo tee /etc/update-motd.d/00-header
    curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/main/MOTD/20-sysinfo | sudo tee /etc/update-motd.d/20-sysinfo
    curl -sSL https://raw.githubusercontent.com/urbancompasspony/server/main/MOTD/90-dynamic-motd | sudo tee /etc/update-motd.d/90-dynamic-motd
    sudo chmod +x /etc/update-motd.d/*
}

function journal0 {
    sleep 3; clear; echo "Ajustando JOURNAL"
    echo -e "
Storage=persistent
SystemMaxUse=5G
SystemKeepFree=10G" | sudo tee -a /etc/systemd/journald.conf
}

function the_end0 {
  clear; echo "Instalação concluida!"
  echo "Reiniciando sistema..."; sleep 3
  sudo reboot
}

function smbconf0 {
  clear; echo "Adicionando modelo SAMBA AD"
  sudo mkdir -p /srv/containers/scripts/
  curl -sSL https://raw.githubusercontent.com/urbancompasspony/docker/main/SAMBA_Model/smbAD.conf | sudo tee /srv/containers/scripts/SMB-AD-Model.conf
}

# ======================================================================================================================================================== #

root_check0
welcome0
bashconf0
timezone0
useless0
update_arm
netplan0
sysctl0
yaml0
motd0
journal0
smbconf0
the_end0

exit 1
