#!/usr/bin/env bash

# ======================================================================================================================================================== #
# curl -L desk.linuxuniverse.com.br | bash
# ======================================================================================================================================================== #

export list01="docker.io ubuntu-restricted-extras ubuntu-restricted-addons net-tools speedtest-cli whois netdiscover iperf arp-scan traceroute trippy \
cifs-utils iotop liblchown-perl p7zip rclone rsnapshot stress lm-sensors cmatrix btop inxi tree dialog btrfs-progs build-essential unrar openvpn curl \
qemu-system qemu-utils qemu-user qemu-kvm qemu-guest-agent libvirt-clients libvirt-daemon-system bridge-utils virt-manager ovmf dnsmasq genisoimage guestfs-tools"

# ======================================================================================================================================================== #

function root_check0 {
  [ "$EUID" -ne 0 ] || {
    clear
    echo "Não execute este script como Root! DICA: Remova o SUDO do comando ou execute-o como usuario local."; echo ""
    exit
  }
}

function welcome0 {
  clear; echo ""; echo "Preparo do Kubuntu 24.04 LTS by SuitIT®"; echo ""
  echo "Insira a senha do usuário $USER"; echo ""
  sudo echo . >/dev/null
  echo ""; echo "5"; sleep 1; echo "4"; sleep 1; echo "3"; sleep 1; echo "2"; sleep 1; echo "1"; sleep 1
}

function bashconf0 {
  clear; echo "Configurando BASH"; echo ""
  curl -sSL https://raw.githubusercontent.com/urbancompasspony/bashrc/main/install.sh | bash
  . .bashrc
}

function timezone0 {
  sudo timedatectl set-timezone Etc/GMT+3
  sudo timedatectl set-local-rtc 1
}

function useless0 {
  clear; echo "Removendo pacotes e desativando servicos inuteis"; echo ""
  sudo apt purge unattended-upgrades -y
  sudo systemctl disable systemd-networkd-wait-online.service
  sudo systemctl mask systemd-networkd-wait-online.service
}

function update0 {
    clear; echo "Atualizando o sistema"; echo ""
    sudo apt update; sudo apt upgrade -y; sudo apt autoremove -y; clear

    echo "Instalando pacotes..."
    sudo apt install $list01 -y &&
    sync &&

    sudo -E usermod -aG docker $USER
}

function sysctl0 {
    sleep 3; clear; echo "Aplicando recursos extras ao SYSCTL"
    echo -e "kernel.sysrq=1
vm.panic_on_oom=1
vm.swappiness=10
kernel.panic=5
#net.ipv4.ip_forward=1
#net.ipv6.conf.all.disable_ipv6=1
#net.ipv6.conf.default.disable_ipv6=1" | sudo tee -a /etc/sysctl.conf &&
}

function fstab0 {
    sudo mkdir /mnt/main
    sudo mkdir /mnt/backup

    sleep 3; clear; echo "Adicionando entradas extras ao fstab"

    echo -e "
# Temp to ram!
tmpfs /tmp tmpfs defaults 0 0
tmpfs /var/tmp tmpfs defaults 0 0

# Main Disk
# /dev/disk/by-uuid/ /mnt/main ext4 defaults 0 0

# Backup
# /dev/disk/by-uuid/ /mnt/backup ext4 defaults 0 0

# Acesso Externo
# //172.25.0.X/folder /mnt/folder cifs credentials=/home/administrador/.smb,iocharset=utf8,file_mode=0777,dir_mode=0777,noperm,user,vers=2.1,nofail,x-systemd.automount,x-systemd.requires=network-online.target,x-systemd.device-timeout=3 0 0" | sudo tee -a /etc/fstab &&
}

# ======================================================================================================================================================== #

root_check0
welcome0
bashconf0
timezone0
useless0
update0
sysctl0

echo "Reiniciando sistema..."; sleep 3
sudo reboot

exit 1
