#!/usr/bin/env bash

# ======================================================================================================================================================== #
# curl -sSL desk.linuxuniverse.com.br | bash
# ======================================================================================================================================================== #

datetime0=$(date '+%Y-%m-%d_%H-%M-%S')
curl -sSL https://raw.githubusercontent.com/urbancompasspony/linite/refs/heads/main/model-desk-run | tee ~/.desk-installer > /dev/null; chmod +x .desk-installer
./.desk-installer 2>&1 | tee ~/.instalacao-$datetime0.log


#wget -O- https://raw.githubusercontent.com/urbancompasspony/linite/refs/heads/main/model-desk-run > ~/.desk-installer
